# vi:syntax=toml
icons = "awesome"

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Dracula by

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#282936"
idle_fg = "#e9e9f4"
info_bg = "#a1efe4"
info_fg = "#282936"
good_bg = "#ebff87"
good_fg = "#282936"
warning_bg = "#00f769"
warning_fg = "#282936"
critical_bg = "#ea61b2"
critical_fg = "#282936"
# The rest of the theme settings are left at default.

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = false
# graph_up = true
interval = 1

[[block]]
block = "backlight"
step_width = 2

[[block]]
block = "time"
format = "%d/%m %R"
timezone = "Asia/Jakarta"
interval = 60

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "toggle"
text = "Caps"
command_on = "xdotool key Caps_Lock"
command_off = "xdotool key Caps_Lock"
command_state = ''' /home/rid9/Project/config/scripts/get_caps.sh '''
interval = 0.5

[[block]]
block = "battery"
upower = true
format = "{percentage}% {time}"
