# vi:syntax=toml
icons = "awesome" 

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# arc-dark-custom by arc-dark-custom

[theme]
name = "plain"

[theme.overrides]
idle_bg = "#303030"
idle_fg = "#eeeeee"
separator_bg = "#303030"
separator_fg = "#eeeeee"
info_bg = "#338dd6"
info_fg = "#303030"
good_bg = "#0095a2"
good_fg = "#303030"
warning_bg = "#bc742d"
warning_fg = "#303030"
critical_bg = "#d8645a"
critical_fg = "#303030"
# The rest of the theme settings are left at default.

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = false
# graph_up = true
interval = 1

[[block]]
block = "backlight"
step_width = 2

[[block]]
block = "time"
format = "%d/%m %R"
timezone = "Asia/Jakarta"
interval = 60

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "toggle"
text = "Caps"
command_on = "xdotool key Caps_Lock"
command_off = "xdotool key Caps_Lock"
command_state = ''' $CONFIG/scripts/get_caps.sh '''
interval = 0.5

[[block]]
block = "battery"
upower = true
format = "{percentage}% {time}"
